#!/bin/bash

# ===================================================================
# MATE Dconf Setup
# URL: https://github.com/e33io/scripts/blob/main/mate-dconf-setup.sh
# ===================================================================

dconf write /ca/desrt/dconf-editor/saved-pathbar-path "'/org/mate/'"
dconf write /ca/desrt/dconf-editor/saved-view "'/org/'"
dconf write /ca/desrt/dconf-editor/window-height "554"
dconf write /ca/desrt/dconf-editor/window-is-maximized "false"
dconf write /ca/desrt/dconf-editor/window-width "878"

dconf write /net/launchpad/plank/docks/dock1/dock-items "['xfce4-appfinder.dockitem', 'caja.dockitem', 'brave-browser.dockitem', 'signal-desktop.dockitem', 'org.gnome.Rhythmbox3.dockitem', 'pluma.dockitem', 'mate-terminal.dockitem', 'matecc.dockitem']"
dconf write /net/launchpad/plank/docks/dock1/hide-mode "'window-dodge'"
dconf write /net/launchpad/plank/docks/dock1/icon-size "42"
dconf write /net/launchpad/plank/docks/dock1/theme "'Transparent'"
dconf write /net/launchpad/plank/docks/dock1/zoom-enabled "true"
dconf write /net/launchpad/plank/docks/dock1/zoom-percent "125"

dconf write /org/ayatana/indicator/notifications/max-items "5"
dconf write /org/ayatana/indicator/session/user-show-menu "false"
dconf write /org/ayatana/indicator/sound/allow-amplified-volume "true"

dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"

dconf write /org/gnome/nm-applet/disable-connected-notifications "true"
dconf write /org/gnome/nm-applet/disable-disconnected-notifications "true"
dconf write /org/gnome/nm-applet/disable-vpn-notifications "true"
dconf write /org/gnome/nm-applet/suppress-wireless-networks-available "true"

dconf write /org/gtk/settings/file-chooser/date-format "'regular'"
dconf write /org/gtk/settings/file-chooser/location-mode "'path-bar'"
dconf write /org/gtk/settings/file-chooser/show-hidden "true"
dconf write /org/gtk/settings/file-chooser/show-size-column "true"
dconf write /org/gtk/settings/file-chooser/show-type-column "true"
dconf write /org/gtk/settings/file-chooser/sidebar-width "157"
dconf write /org/gtk/settings/file-chooser/sort-column "'name'"
dconf write /org/gtk/settings/file-chooser/sort-directories-first "true"
dconf write /org/gtk/settings/file-chooser/sort-order "'ascending'"
dconf write /org/gtk/settings/file-chooser/type-format "'category'"
dconf write /org/gtk/settings/file-chooser/window-position "(299, 251)"
dconf write /org/gtk/settings/file-chooser/window-size "(827, 556)"

dconf write /org/mate/caja/desktop/font "'Inter 9'"
dconf write /org/mate/caja/desktop/home-icon-visible "false"
dconf write /org/mate/caja/desktop/volumes-visible "false"

dconf write /org/mate/caja/list-view/default-column-order "['name', 'type', 'size', 'date_modified', 'date_accessed', 'date_created', 'extension', 'group', 'where', 'mime_type', 'octal_permissions', 'owner', 'permissions', 'selinux_context', 'size_on_disk']"
dconf write /org/mate/caja/list-view/default-visible-columns "['name', 'type', 'size', 'date_modified']"

dconf write /org/mate/caja/preferences/always-use-location-entry "false"
dconf write /org/mate/caja/preferences/date-format "'iso'"
dconf write /org/mate/caja/preferences/default-folder-viewer "'list-view'"
dconf write /org/mate/caja/preferences/executable-text-activation "'display'"
dconf write /org/mate/caja/preferences/show-hidden-files "true"
dconf write /org/mate/caja/preferences/thumbnail-limit "uint64 4294967295"

dconf write /org/mate/caja/window-state/geometry "'757x575+200+173'"
dconf write /org/mate/caja/window-state/maximized "false"
dconf write /org/mate/caja/window-state/sidebar-width "78"
dconf write /org/mate/caja/window-state/start-with-sidebar "true"
dconf write /org/mate/caja/window-state/start-with-status-bar "true"
dconf write /org/mate/caja/window-state/start-with-toolbar "true"

dconf write /org/mate/desktop/accessibility/keyboard/bouncekeys-beep-reject "true"
dconf write /org/mate/desktop/accessibility/keyboard/bouncekeys-delay "300"
dconf write /org/mate/desktop/accessibility/keyboard/bouncekeys-enable "false"
dconf write /org/mate/desktop/accessibility/keyboard/enable "false"
dconf write /org/mate/desktop/accessibility/keyboard/feature-state-change-beep "false"
dconf write /org/mate/desktop/accessibility/keyboard/mousekeys-accel-time "1200"
dconf write /org/mate/desktop/accessibility/keyboard/mousekeys-enable "false"
dconf write /org/mate/desktop/accessibility/keyboard/mousekeys-init-delay "160"
dconf write /org/mate/desktop/accessibility/keyboard/mousekeys-max-speed "750"
dconf write /org/mate/desktop/accessibility/keyboard/slowkeys-beep-accept "true"
dconf write /org/mate/desktop/accessibility/keyboard/slowkeys-beep-press "true"
dconf write /org/mate/desktop/accessibility/keyboard/slowkeys-beep-reject "false"
dconf write /org/mate/desktop/accessibility/keyboard/slowkeys-delay "300"
dconf write /org/mate/desktop/accessibility/keyboard/slowkeys-enable "false"
dconf write /org/mate/desktop/accessibility/keyboard/stickykeys-enable "false"
dconf write /org/mate/desktop/accessibility/keyboard/stickykeys-latch-to-lock "true"
dconf write /org/mate/desktop/accessibility/keyboard/stickykeys-modifier-beep "true"
dconf write /org/mate/desktop/accessibility/keyboard/stickykeys-two-key-off "true"
dconf write /org/mate/desktop/accessibility/keyboard/timeout "120"
dconf write /org/mate/desktop/accessibility/keyboard/timeout-enable "false"
dconf write /org/mate/desktop/accessibility/keyboard/togglekeys-enable "false"

dconf write /org/mate/desktop/applications/calculator/exec "'mate-calc'"
dconf write /org/mate/desktop/applications/messenger/exec "'/opt/Signal/signal-desktop'"
dconf write /org/mate/desktop/applications/terminal/exec "'mate-terminal'"

dconf write /org/mate/desktop/background/color-shading-type "'vertical-gradient'"
dconf write /org/mate/desktop/background/picture-filename "'/usr/share/wallpapers/background.png'"
dconf write /org/mate/desktop/background/picture-options "'zoom'"
dconf write /org/mate/desktop/background/primary-color "'rgb(88,145,188)'"
dconf write /org/mate/desktop/background/secondary-color "'rgb(60,143,37)'"
dconf write /org/mate/desktop/background/show-desktop-icons "true"

dconf write /org/mate/desktop/font-rendering/antialiasing "'rgba'"
dconf write /org/mate/desktop/font-rendering/hinting "'slight'"

dconf write /org/mate/desktop/interface/document-font-name "'Inter 10'"
dconf write /org/mate/desktop/interface/font-name "'Inter 9'"
dconf write /org/mate/desktop/interface/gtk-color-scheme "'tooltip_fg_color:#f7f7f7\ntooltip_bg_color:#353535'"
dconf write /org/mate/desktop/interface/gtk-decoration-layout "'menu:minimize,maximize,close'"
dconf write /org/mate/desktop/interface/gtk-theme "'Yaru-dark'"
dconf write /org/mate/desktop/interface/icon-theme "'Papirus-Dark'"
dconf write /org/mate/desktop/interface/monospace-font-name "'SovranMono 10'"

dconf write /org/mate/desktop/keybindings/custom0/action "'xfce4-appfinder'"
dconf write /org/mate/desktop/keybindings/custom0/binding "'<Mod4>d'"
dconf write /org/mate/desktop/keybindings/custom0/name "'Application Finder'"

dconf write /org/mate/desktop/keybindings/custom1/action "'pluma'"
dconf write /org/mate/desktop/keybindings/custom1/binding "'<Mod4>t'"
dconf write /org/mate/desktop/keybindings/custom1/name "'Text Editor'"

dconf write /org/mate/desktop/keybindings/custom2/action "'/opt/Signal/signal-desktop'"
dconf write /org/mate/desktop/keybindings/custom2/binding "'<Mod4>c'"
dconf write /org/mate/desktop/keybindings/custom2/name "'Signal App'"

dconf write /org/mate/desktop/keybindings/custom3/action "'mate-screenshot --area'"
dconf write /org/mate/desktop/keybindings/custom3/binding "'<Shift>Print'"
dconf write /org/mate/desktop/keybindings/custom3/name "'Take a screenshot of an area'"

dconf write /org/mate/desktop/media-handling/automount-open "false"

dconf write /org/mate/desktop/peripherals/keyboard/numlock-state "'off'"
dconf write /org/mate/desktop/peripherals/mouse/cursor-theme "'Yaru'"

dconf write /org/mate/desktop/session/idle-delay "5"
dconf write /org/mate/desktop/session/session-start "1750483086"
dconf write /org/mate/desktop/session/show-hidden-apps "true"

dconf write /org/mate/engrampa/dialogs/batch-add/default-extension "'.zip'"

dconf write /org/mate/engrampa/general/encrypt-header "false"
dconf write /org/mate/engrampa/general/unar-open-zip "false"

dconf write /org/mate/engrampa/listing/list-mode "'as-folder'"
dconf write /org/mate/engrampa/listing/show-path "false"
dconf write /org/mate/engrampa/listing/sort-method "'name'"
dconf write /org/mate/engrampa/listing/sort-type "'ascending'"

dconf write /org/mate/marco/general/action-double-click-titlebar "'toggle_maximize'"
dconf write /org/mate/marco/general/button-layout "'menu:minimize,maximize,close'"
dconf write /org/mate/marco/general/compositing-fast-alt-tab "true"
dconf write /org/mate/marco/general/focus-mode "'sloppy'"
dconf write /org/mate/marco/general/mouse-button-modifier "'<Super>'"
dconf write /org/mate/marco/general/num-workspaces "6"
dconf write /org/mate/marco/general/show-tab-border "false"
dconf write /org/mate/marco/general/theme "'Yaru-dark'"
dconf write /org/mate/marco/general/titlebar-font "'Inter 9'"
dconf write /org/mate/marco/general/wrap-style "'no wrap'"

dconf write /org/mate/marco/global-keybindings/cycle-group "'disabled'"
dconf write /org/mate/marco/global-keybindings/cycle-panels "'disabled'"
dconf write /org/mate/marco/global-keybindings/cycle-windows "'disabled'"
dconf write /org/mate/marco/global-keybindings/panel-main-menu "'disabled'"
dconf write /org/mate/marco/global-keybindings/panel-run-dialog "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-1 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-2 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-3 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-4 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-5 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-6 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-7 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-8 "'disabled'"
dconf write /org/mate/marco/global-keybindings/run-command-terminal "'<Mod4>Return'"
dconf write /org/mate/marco/global-keybindings/switch-panels "'disabled'"
dconf write /org/mate/marco/global-keybindings/switch-to-workspace-1 "'<Mod4>1'"
dconf write /org/mate/marco/global-keybindings/switch-to-workspace-2 "'<Mod4>2'"
dconf write /org/mate/marco/global-keybindings/switch-to-workspace-3 "'<Mod4>3'"
dconf write /org/mate/marco/global-keybindings/switch-to-workspace-4 "'<Mod4>4'"
dconf write /org/mate/marco/global-keybindings/switch-to-workspace-5 "'<Mod4>5'"
dconf write /org/mate/marco/global-keybindings/switch-to-workspace-6 "'<Mod4>6'"

dconf write /org/mate/marco/keybinding-commands/command-1 "''"
dconf write /org/mate/marco/keybinding-commands/command-2 "''"
dconf write /org/mate/marco/keybinding-commands/command-3 "''"
dconf write /org/mate/marco/keybinding-commands/command-4 "''"
dconf write /org/mate/marco/keybinding-commands/command-5 "''"
dconf write /org/mate/marco/keybinding-commands/command-6 "''"
dconf write /org/mate/marco/keybinding-commands/command-7 "''"
dconf write /org/mate/marco/keybinding-commands/command-8 "''"

dconf write /org/mate/marco/window-keybindings/begin-move "'disabled'"
dconf write /org/mate/marco/window-keybindings/begin-resize "'disabled'"
dconf write /org/mate/marco/window-keybindings/close "'<Shift><Mod4>q'"
dconf write /org/mate/marco/window-keybindings/maximize "'disabled'"
dconf write /org/mate/marco/window-keybindings/maximize-horizontally "'<Shift><Mod4>h'"
dconf write /org/mate/marco/window-keybindings/maximize-vertically "'<Shift><Mod4>v'"
dconf write /org/mate/marco/window-keybindings/minimize "'<Shift><Mod4>i'"
dconf write /org/mate/marco/window-keybindings/move-to-center "'<Shift><Mod4>space'"
dconf write /org/mate/marco/window-keybindings/move-to-side-n "'disabled'"
dconf write /org/mate/marco/window-keybindings/move-to-side-s "'disabled'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-1 "'<Shift><Mod4>exclam'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-2 "'<Shift><Mod4>at'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-3 "'<Shift><Mod4>numbersign'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-4 "'<Shift><Mod4>dollar'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-5 "'<Shift><Mod4>percent'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-6 "'<Shift><Mod4>asciicircum'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-down "'disabled'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-left "'<Shift><Mod4>Left'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-right "'<Shift><Mod4>Right'"
dconf write /org/mate/marco/window-keybindings/move-to-workspace-up "'disabled'"
dconf write /org/mate/marco/window-keybindings/tile-to-corner-ne "'disabled'"
dconf write /org/mate/marco/window-keybindings/tile-to-corner-nw "'disabled'"
dconf write /org/mate/marco/window-keybindings/tile-to-corner-se "'disabled'"
dconf write /org/mate/marco/window-keybindings/tile-to-corner-sw "'disabled'"
dconf write /org/mate/marco/window-keybindings/toggle-fullscreen "'<Shift><Mod4>f'"
dconf write /org/mate/marco/window-keybindings/toggle-maximized "'<Shift><Mod4>m'"
dconf write /org/mate/marco/window-keybindings/toggle-shaded "'disabled'"
dconf write /org/mate/marco/window-keybindings/unmaximize "'disabled'"

dconf write /org/mate/notification-daemon/popup-location "'top_right'"
dconf write /org/mate/notification-daemon/theme "'slider'"

dconf write /org/mate/panel/general/object-id-list "['menu-bar', 'object-1', 'object-2', 'object-0']"
dconf write /org/mate/panel/general/toplevel-id-list "['top']"

dconf write /org/mate/panel/menubar/icon-size "'default'"

dconf write /org/mate/panel/objects/menu-bar/locked "true"
dconf write /org/mate/panel/objects/menu-bar/object-type "'menu-bar'"
dconf write /org/mate/panel/objects/menu-bar/position "0"
dconf write /org/mate/panel/objects/menu-bar/toplevel-id "'top'"

dconf write /org/mate/panel/objects/object-0/applet-iid "'WnckletFactory::WorkspaceSwitcherApplet'"
dconf write /org/mate/panel/objects/object-0/locked "true"
dconf write /org/mate/panel/objects/object-0/object-type "'applet'"
dconf write /org/mate/panel/objects/object-0/position "102"
dconf write /org/mate/panel/objects/object-0/relative-to-edge "'end'"
dconf write /org/mate/panel/objects/object-0/toplevel-id "'top'"

dconf write /org/mate/panel/objects/object-0/prefs/wrap-workspaces "true"

dconf write /org/mate/panel/objects/object-1/applet-iid "'ClockAppletFactory::ClockApplet'"
dconf write /org/mate/panel/objects/object-1/locked "true"
dconf write /org/mate/panel/objects/object-1/object-type "'applet'"
dconf write /org/mate/panel/objects/object-1/position "0"
dconf write /org/mate/panel/objects/object-1/relative-to-edge "'center'"
dconf write /org/mate/panel/objects/object-1/toplevel-id "'top'"

dconf write /org/mate/panel/objects/object-1/prefs/custom-format "''"
dconf write /org/mate/panel/objects/object-1/prefs/format "'24-hour'"
dconf write /org/mate/panel/objects/object-1/prefs/show-seconds "true"
dconf write /org/mate/panel/objects/object-1/prefs/show-temperature "false"
dconf write /org/mate/panel/objects/object-1/prefs/show-weather "false"
dconf write /org/mate/panel/objects/object-1/prefs/show-week-numbers "false"
dconf write /org/mate/panel/objects/object-1/prefs/speed-unit "'mph'"
dconf write /org/mate/panel/objects/object-1/prefs/temperature-unit "'Fahrenheit'"

dconf write /org/mate/panel/objects/object-2/applet-iid "'IndicatorAppletCompleteFactory::IndicatorAppletComplete'"
dconf write /org/mate/panel/objects/object-2/locked "true"
dconf write /org/mate/panel/objects/object-2/object-type "'applet'"
dconf write /org/mate/panel/objects/object-2/position "0"
dconf write /org/mate/panel/objects/object-2/relative-to-edge "'end'"
dconf write /org/mate/panel/objects/object-2/toplevel-id "'top'"

dconf write /org/mate/panel/toplevels/top/enable-buttons "false"
dconf write /org/mate/panel/toplevels/top/expand "true"
dconf write /org/mate/panel/toplevels/top/orientation "'top'"
dconf write /org/mate/panel/toplevels/top/screen "0"
dconf write /org/mate/panel/toplevels/top/size "24"

dconf write /org/mate/pluma/background-pattern "'none'"
dconf write /org/mate/pluma/bottom-panel-size "140"
dconf write /org/mate/pluma/bracket-matching "false"
dconf write /org/mate/pluma/color-scheme "'monokai-mod'"
dconf write /org/mate/pluma/display-right-margin "false"
dconf write /org/mate/pluma/highlight-current-line "false"
dconf write /org/mate/pluma/side-panel-active-page "827629879"
dconf write /org/mate/pluma/side-panel-size "200"
dconf write /org/mate/pluma/size "(837, 735)"
dconf write /org/mate/pluma/state "128"
dconf write /org/mate/pluma/statusbar-visible "true"

dconf write /org/mate/pluma/plugins/filebrowser/on-load/root "'file:///'"
dconf write /org/mate/pluma/plugins/filebrowser/on-load/tree-view "true"

dconf write /org/mate/power-manager/button-lid-ac "'suspend'"
dconf write /org/mate/power-manager/button-power "'interactive'"
dconf write /org/mate/power-manager/button-suspend "'suspend'"
dconf write /org/mate/power-manager/sleep-display-ac "600"

dconf write /org/mate/screensaver/mode "'single'"
dconf write /org/mate/screensaver/picture-filename "'/usr/share/wallpapers/background.png'"
dconf write /org/mate/screensaver/themes "['screensavers-footlogo-floaters']"

dconf write /org/mate/screenshot/include-pointer "false"

dconf write /org/mate/search-tool/default-window-height "353"
dconf write /org/mate/search-tool/default-window-maximized "false"
dconf write /org/mate/search-tool/default-window-width "554"

dconf write /org/mate/search-tool/select/contains-the-text "true"

dconf write /org/mate/settings-daemon/plugins/media-keys/home "'<Shift><Mod4>Return'"
dconf write /org/mate/settings-daemon/plugins/media-keys/magnifier "'disabled'"
dconf write /org/mate/settings-daemon/plugins/media-keys/on-screen-keyboard "'disabled'"
dconf write /org/mate/settings-daemon/plugins/media-keys/power "'<Mod4>p'"
dconf write /org/mate/settings-daemon/plugins/media-keys/screenreader "'disabled'"
dconf write /org/mate/settings-daemon/plugins/media-keys/screensaver "'<Mod4>x'"
dconf write /org/mate/settings-daemon/plugins/media-keys/www "'<Mod4>b'"

dconf write /org/mate/system-monitor/current-tab "2"
dconf write /org/mate/system-monitor/maximized "false"
dconf write /org/mate/system-monitor/window-state "(762, 574, 582, 237)"

dconf write /org/mate/system-monitor/disktreenew/col-7-width "300"

dconf write /org/mate/system-monitor/proctree/col-0-width "291"
dconf write /org/mate/system-monitor/proctree/col-12-width "43"
dconf write /org/mate/system-monitor/proctree/col-15-visible "true"
dconf write /org/mate/system-monitor/proctree/col-15-width "79"
dconf write /org/mate/system-monitor/proctree/col-16-visible "false"
dconf write /org/mate/system-monitor/proctree/col-16-width "125"
dconf write /org/mate/system-monitor/proctree/col-17-visible "false"
dconf write /org/mate/system-monitor/proctree/col-17-width "599"
dconf write /org/mate/system-monitor/proctree/col-19-visible "false"
dconf write /org/mate/system-monitor/proctree/col-19-width "195"
dconf write /org/mate/system-monitor/proctree/col-2-width "68"
dconf write /org/mate/system-monitor/proctree/col-3-visible "false"
dconf write /org/mate/system-monitor/proctree/col-4-visible "false"
dconf write /org/mate/system-monitor/proctree/col-5-visible "false"
dconf write /org/mate/system-monitor/proctree/col-6-visible "false"
dconf write /org/mate/system-monitor/proctree/col-8-width "72"
dconf write /org/mate/system-monitor/proctree/col-9-width "89"
dconf write /org/mate/system-monitor/proctree/columns-order "[0, 1, 2, 15, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]"
dconf write /org/mate/system-monitor/proctree/sort-col "15"
dconf write /org/mate/system-monitor/proctree/sort-order "0"

dconf write /org/mate/terminal/global/confirm-window-close "false"

dconf write /org/mate/terminal/profiles/default/allow-bold "true"
dconf write /org/mate/terminal/profiles/default/background-color "'#1E1E1E1E1E1E'"
dconf write /org/mate/terminal/profiles/default/bold-color "'#000000000000'"
dconf write /org/mate/terminal/profiles/default/cursor-blink-mode "'on'"
dconf write /org/mate/terminal/profiles/default/default-show-menubar "false"
dconf write /org/mate/terminal/profiles/default/default-size-columns "104"
dconf write /org/mate/terminal/profiles/default/default-size-rows "32"
dconf write /org/mate/terminal/profiles/default/font "'SovranMono 10'"
dconf write /org/mate/terminal/profiles/default/foreground-color "'#DDDDDDDDDDDD'"
dconf write /org/mate/terminal/profiles/default/palette "'#0F0F0F0F0F0F:#FBFB2C2B6767:#3535B4B45151:#FCFCE1E14F4F:#2322A09FDEDE:#84837878DFDF:#2222CAC9CBCB:#CCCCCCCCCCCC:#FDFD93935353:#FCFC61618D8D:#5353CCCC6D6C:#FCFCE5E56666:#4D4DB2B1E4E4:#94938A8AE3E3:#403FDEDEDFDF:#DDDDDDDDDDDD'"
dconf write /org/mate/terminal/profiles/default/scrollback-lines "4000"
dconf write /org/mate/terminal/profiles/default/scrollbar-position "'hidden'"
dconf write /org/mate/terminal/profiles/default/use-custom-default-size "true"
dconf write /org/mate/terminal/profiles/default/use-system-font "false"
dconf write /org/mate/terminal/profiles/default/use-theme-colors "false"
dconf write /org/mate/terminal/profiles/default/visible-name "'Default'"
